//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikePost
    {
        public int LikePostID { get; set; }
        public System.DateTime DateOfAction { get; set; }
        public int ID_Post { get; set; }
        public int ID_PersonThatLikesPost { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Post Post { get; set; }
    }
}
