//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientsOfPM
    {
        public int RecipientsOfPMID { get; set; }
        public int ID_PrivateMessage { get; set; }
        public int ID_Recipient { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PrivateMessage PrivateMessage { get; set; }
    }
}
