//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thumbnail
    {
        public int ThumbnailID { get; set; }
        public string ImagePath { get; set; }
        public int ID_Post { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
