//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniBirdEntities : DbContext
    {
        public MiniBirdEntities()
            : base("name=MiniBirdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hashtag> Hashtag { get; set; }
        public virtual DbSet<LikePost> LikePost { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<RePost> RePost { get; set; }
        public virtual DbSet<Thumbnail> Thumbnail { get; set; }
    }
}
